ALTER TABLE Member MODIFY ID INT NOT NULL;
ALTER TABLE Member DROP PRIMARY KEY;
DROP TABLE Member;

ALTER TABLE Project MODIFY ID INT NOT NULL;
ALTER TABLE Project DROP PRIMARY KEY;
DROP TABLE Project;

ALTER TABLE Sensor MODIFY ID INT NOT NULL;
ALTER TABLE Sensor DROP PRIMARY KEY;
DROP TABLE Sensor;

ALTER TABLE Arduino MODIFY ID INT NOT NULL;
ALTER TABLE Arduino DROP PRIMARY KEY;
DROP TABLE Arduino;

ALTER TABLE Location MODIFY ID INT NOT NULL;
ALTER TABLE Location DROP PRIMARY KEY;
DROP TABLE Location;

ALTER TABLE Status MODIFY ID INT NOT NULL;
ALTER TABLE Status DROP PRIMARY KEY;
DROP TABLE Status;

ALTER TABLE DataInfo MODIFY ID INT NOT NULL;
ALTER TABLE DataInfo DROP PRIMARY KEY;
DROP TABLE DataInfo;

ALTER TABLE Alert MODIFY ID INT NOT NULL;
ALTER TABLE Alert DROP PRIMARY KEY;
DROP TABLE Alert;

ALTER TABLE TypeAlert MODIFY ID INT NOT NULL;
ALTER TABLE TypeAlert DROP PRIMARY KEY;
DROP TABLE TypeAlert;

ALTER TABLE Family MODIFY ID INT NOT NULL;
ALTER TABLE Family DROP PRIMARY KEY;
DROP TABLE Family;

ALTER TABLE Member_Project MODIFY ID INT NOT NULL;
ALTER TABLE Member_Project DROP PRIMARY KEY;
ALTER TABLE Member_Project DROP FOREIGN KEY FK_Member_Project_Member;
ALTER TABLE Member_Project DROP FOREIGN KEY FK_Member_Project_Project;
DROP TABLE Member_Project;

ALTER TABLE Project_Sensor MODIFY ID INT NOT NULL;
ALTER TABLE Project_Sensor DROP PRIMARY KEY;
ALTER TABLE Project_Sensor DROP FOREIGN KEY FK_Project_Sensor_Project;
ALTER TABLE Project_Sensor DROP FOREIGN KEY FK_Project_Sensor_Sensor;
DROP TABLE Project_Sensor;

ALTER TABLE Sensor_Arduino MODIFY ID INT NOT NULL;
ALTER TABLE Sensor_Arduino DROP PRIMARY KEY;
ALTER TABLE Sensor_Arduino DROP FOREIGN KEY FK_Sensor_Arduino_Sensor;
ALTER TABLE Sensor_Arduino DROP FOREIGN KEY FK_Sensor_Arduino_Arduino;
DROP TABLE Sensor_Arduino;

ALTER TABLE Sensor_Location MODIFY ID INT NOT NULL;
ALTER TABLE Sensor_Location DROP PRIMARY KEY;
ALTER TABLE Sensor_Location DROP FOREIGN KEY FK_Sensor_Location_Sensor;
ALTER TABLE Sensor_Location DROP FOREIGN KEY FK_Sensor_Location_Location;
DROP TABLE Sensor_Location;

ALTER TABLE Sensor_Status MODIFY ID INT NOT NULL;
ALTER TABLE Sensor_Status DROP PRIMARY KEY;
ALTER TABLE Sensor_Status DROP FOREIGN KEY FK_Sensor_Status_Sensor;
ALTER TABLE Sensor_Status DROP FOREIGN KEY FK_Sensor_Status_Status;
DROP TABLE Sensor_Status;

ALTER TABLE Sensor_DataInfo MODIFY ID INT NOT NULL;
ALTER TABLE Sensor_DataInfo DROP PRIMARY KEY;
ALTER TABLE Sensor_DataInfo DROP FOREIGN KEY FK_Sensor_DataInfo_Sensor;
ALTER TABLE Sensor_DataInfo DROP FOREIGN KEY FK_Sensor_DataInfo_DataInfo;
DROP TABLE Sensor_DataInfo;

ALTER TABLE DataInfo_Alert MODIFY ID INT NOT NULL;
ALTER TABLE DataInfo_Alert DROP PRIMARY KEY;
ALTER TABLE DataInfo_Alert DROP FOREIGN KEY FK_DataInfo_Alert_DataInfo;
ALTER TABLE DataInfo_Alert DROP FOREIGN KEY FK_DataInfo_Alert_Alert;
DROP TABLE DataInfo_Alert;

ALTER TABLE Sensor_Status MODIFY ID INT NOT NULL;
ALTER TABLE Alert_TypeAlert DROP PRIMARY KEY;
ALTER TABLE Alert_TypeAlert DROP FOREIGN KEY FK_Alert_TypeAlert_Alert;
ALTER TABLE Alert_TypeAlert DROP FOREIGN KEY FK_Alert_TypeAlert_TypeAlert;
DROP TABLE Alert_TypeAlert;

ALTER TABLE Alert_Family MODIFY ID INT NOT NULL;
ALTER TABLE Alert_Family DROP PRIMARY KEY;
ALTER TABLE Alert_Family DROP FOREIGN KEY FK_Alert_Family_Alert;
ALTER TABLE Alert_Family DROP FOREIGN KEY FK_Alert_Family_Family;
DROP TABLE Alert_Family;


